# Generated by Django 2.2 on 2019-06-29 22:32

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier of an object', primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time an object was created')),
                ('updated', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time an object was updated')),
                ('email', models.EmailField(help_text='Email of the person to be notified', max_length=254, unique=True)),
                ('areas', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, help_text='Areas to be searched for in the extracted PDFs', size=None)),
                ('is_active', models.BooleanField()),
            ],
            options={
                'abstract': False,
                'ordering': ('-updated', '-created'),
            },
        ),
    ]
