# Generated by Django 2.2 on 2019-07-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20190701_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')], max_length=7),
        ),
    ]
