# Generated by Django 2.2 on 2019-06-23 11:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import kplc_interruptions.interruptions.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interruption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier of an object', primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time an object was created')),
                ('updated', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time an object was updated')),
                ('title', models.CharField(help_text='Title of the interruption link', max_length=255)),
                ('link', models.URLField(help_text='URL to the PDF file(s) containing the interruptions', max_length=255)),
            ],
            options={
                'abstract': False,
                'unique_together': {('title', 'link')},
                'ordering': ('-updated', '-created'),
            },
        ),
        migrations.CreateModel(
            name='InterruptionPdf',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier of an object', primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time an object was created')),
                ('updated', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time an object was updated')),
                ('pdf_file', models.FileField(help_text="PDF downloaded from KPLC's website", upload_to=kplc_interruptions.interruptions.models.interruption_upload_path)),
                ('pdf_name', models.CharField(help_text='Name displayed of the PDF', max_length=255)),
                ('pdf_link', models.URLField(help_text='URL to download the PDF', max_length=255)),
                ('interruption', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interruption_pdfs', to='interruptions.Interruption')),
            ],
            options={
                'abstract': False,
                'unique_together': {('interruption', 'pdf_link')},
                'ordering': ('-updated', '-created'),
            },
        ),
    ]
