# Generated by Django 2.2 on 2019-06-23 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interruptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interruptionpdf',
            old_name='pdf_name',
            new_name='pdf_link_name',
        ),
    ]
