# Generated by Django 2.2 on 2019-06-24 18:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('interruptions', '0002_auto_20190623_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterruptionPdfText',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier of an object', primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time an object was created')),
                ('updated', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time an object was updated')),
                ('pdf_text', models.TextField()),
                ('pdf', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pdf_text', to='interruptions.InterruptionPdf')),
            ],
            options={
                'ordering': ('-updated', '-created'),
                'abstract': False,
            },
        ),
    ]
